services:
  postgres:
    image: postgres:16-alpine
    container_name: shortly-postgres
    environment:
      POSTGRES_DB: shortly
      POSTGRES_USER: sagargupta
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortly -d shortly"]
      interval: 2s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: shortly-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
